name: npm publish

on:
  push:
    tags:
      - 'react-helsinki-notification-manager-v*.*.*'

jobs:
  publish-npm-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm install -g npm@latest
      - run: yarn --frozen-lockfile
      - run: yarn test  
      - run: yarn build
      - run: npm publish --access public
        env:
          NPM_CONFIG_PROVENANCE: true
