name: npm publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@feat/registry-publish-workflows
        with:
          node-version: '22'
          use-yarn: true
      - name: Publish
        uses: City-of-Helsinki/.github/.github/workflows/ci-npm-publish.yml@feat/registry-publish-workflows
        with:
          node-version: '22'
          use-ci-build: true
