name: npm-publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@feat/registry-publish-workflows
    with:
      node-version: '22'
  publish:
    uses: City-of-Helsinki/.github/.github/workflows/ci-npm-publish.yml@feat/registry-publish-workflows
    with:
      node-version: '22'
      use-ci-build: true
